# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_age', models.CharField(max_length=3)),
                ('level_of_education', models.CharField(choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ES', 'Ensino Superior'), ('MT', 'Mestrado'), ('DT', 'Doutorado')], max_length=2)),
                ('level_of_english', models.CharField(choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3)),
                ('level_of_literature', models.CharField(choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3)),
                ('level_of_history', models.CharField(choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3)),
                ('level_of_biology', models.CharField(choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3)),
                ('level_of_physics', models.CharField(choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3)),
                ('level_of_math', models.CharField(choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3)),
                ('learning_goal', models.CharField(choices=[('STL', 'Aprendizagem a curto prazo'), ('LLL', 'Aprendizagem vitalícia')], help_text="'Aprendizagem a curto prazo' = aprender sobre um tópico específico;\n                                               'Aprendizagem vitalícia' = aprender mais sobre uma matéria;", max_length=3)),
                ('learning_style', models.CharField(choices=[('SQN', 'Aprendizagem sequencial'), ('GLB', 'Aprendizagem global')], help_text='"Aprendizagem sequencial = aprende linearmente (ex. lê um livro na sequência capítulo 1,2,3...)\n                                                    Aprendizagem global = aprende pulando conteúdo (ex. lê o livro em ordem randômica cap. 1,5,3,9...)', max_length=3)),
            ],
        ),
    ]
