# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_description', models.TextField(max_length=1000)),
                ('movie_pic', models.ImageField(upload_to='pics/')),
                ('movie_knowledge_area', models.CharField(max_length=100)),
                ('movie_recommended_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('context_time', models.DateTimeField(null=True, verbose_name='Date Rated')),
                ('long', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.models.User')),
            ],
        ),
    ]
