# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20170906_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='learning_goal',
            field=models.CharField(blank=True, choices=[('STL', 'Aprendizagem a curto prazo'), ('LLL', 'Aprendizagem vitalícia')], help_text="'Aprendizagem a curto prazo' = aprender sobre um tópico específico;\n                                               'Aprendizagem vitalícia' = aprender mais sobre uma matéria;", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('SQN', 'Aprendizagem sequencial'), ('GLB', 'Aprendizagem global')], help_text='"Aprendizagem sequencial = aprende linearmente (ex. lê um livro na sequência capítulo 1,2,3...)\n                                                    Aprendizagem global = aprende pulando conteúdo (ex. lê o livro em ordem randômica cap. 1,5,3,9...)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level_of_biology',
            field=models.CharField(blank=True, choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio'), ('ES', 'Ensino Superior'), ('MT', 'Mestrado'), ('DT', 'Doutorado')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level_of_english',
            field=models.CharField(blank=True, choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level_of_history',
            field=models.CharField(blank=True, choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level_of_literature',
            field=models.CharField(blank=True, choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level_of_math',
            field=models.CharField(blank=True, choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='level_of_physics',
            field=models.CharField(blank=True, choices=[('LL', 'Baixo'), ('ML', 'Médio'), ('HL', 'Alto')], max_length=3, null=True),
        ),
    ]
