# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(),
        ),
    ]
