# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20170831_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='context_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Rated'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
