# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20170906_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='user',
            new_name='user_pk',
        ),
    ]
