# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20170907_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='user_pk',
            new_name='user_fk',
        ),
    ]
