# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20170831_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_knowledge_area',
            field=models.CharField(choices=[('EN', 'Inglês'), ('LT', 'Literatura'), ('HT', 'História'), ('BL', 'Biologia'), ('PH', 'Física'), ('MT', 'Matémática')], max_length=2),
        ),
    ]
