# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20170901_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='predicted_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
