# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20170907_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='user_age',
            new_name='learner_age',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='learner',
        ),
    ]
