# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20170911_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='context_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Rated'),
        ),
    ]
