# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_auto_20170911_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_knowledge_area',
            field=models.CharField(blank=True, choices=[('EN', 'Inglês'), ('LT', 'Literatura'), ('HT', 'História'), ('BL', 'Biologia'), ('PH', 'Física'), ('MT', 'Matémática')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_recommended_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
