# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_auto_20170912_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='rating',
            name='predicted_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
