# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_auto_20170912_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='predicted_rating',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
