# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_auto_20170922_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='learning_goal',
            field=models.CharField(blank=True, choices=[('STL', 'Aprendizagem a curto prazo'), ('LLL', 'Aprendizagem vitalícia')], help_text="'Aprendizagem a curto prazo' = aprender sobre um topico especifico;\n                                               'Aprendizagem vitalicia' = aprender mais sobre uma materia;", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learning_style',
            field=models.CharField(blank=True, choices=[('SQN', 'Aprendizagem sequencial'), ('GLB', 'Aprendizagem global')], help_text='"Aprendizagem sequencial = aprende linearmente (ex. le um livro na sequencia capitulo 1,2,3...)\n                                                    Aprendizagem global = aprende pulando conteudo (ex. le o livro em ordem randomica cap. 1,5,3,9...)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='benefits',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_knowledge_area',
            field=models.CharField(blank=True, choices=[('EN', 'Inglês'), ('LT', 'Literatura'), ('HT', 'História'), ('BL', 'Biologia'), ('PH', 'Física'), ('MT', 'Matemática')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='objectives',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='problems',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rationale',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
